### ISSUE TITLE
I am getting error "org.openqa.selenium.WebDriverException: Unable to parse remote response: " and I don't know how to solve this. So guys could you please help me

### ISSUE THREAD

**Issue by QA-Selenium** [QA-Selenium/Sample#1]
Hello everyone,

I am learning Selenium. So I was trying to run parallel execution via Grid. And I got below error. I have mentioned the complete error detail below. Please help me to solve it.

org.openqa.selenium.WebDriverException: Unable to parse remote response: <html><head><script src='/grid/resources/org/openqa/grid/images/jquery-3.1.1.min.js'></script><script src='/grid/resources/org/openqa/grid/images/consoleservlet.js'></script><link href='/grid/resources/org/openqa/grid/images/consoleservlet.css' rel='stylesheet' type='text/css' /><link href='/grid/resources/org/openqa/grid/images/favicon.ico' rel='icon' type='image/x-icon' /><title>Grid Console</title><style>.busy { opacity : 0.4;filter: alpha(opacity=40);}</style></head><body><div id='main-content'><div id='header'><h1><a href='/grid/console'>Selenium</a></h1><h2>Grid Console v.3.141.59</h2><div><a id='helplink' target='_blank' href='https://github.com/SeleniumHQ/selenium/wiki/Grid2'>Help</a></div></div><div id='left-column'><div class='proxy'><p class='proxyname'>DefaultRemoteProxy (version : 3.141.59)<p class='proxyid'>id : http://192.168.1.100:5555, OS : WIN10</p><div class='tabs'><ul><li class='tab' type='browsers'><a title='test slots' href='#'>Browsers</a></li><li class='tab' type='config'><a title='node configuration' href='#'>Configuration</a></li></ul></div><div class='content'><div type='browsers' class='content_detail'><p class='protocol' >WebDriver</p><p>v:<img src='/grid/resources/org/openqa/grid/images/firefox.png' width='16' height='16' title='{server:CONFIG_UUID=3e72bd4c-f8e2-431b-b3fc-bd103dda68d3, seleniumProtocol=WebDriver, browserName=firefox, maxInstances=4, platformName=WIN10, platform=WIN10}' />
<img src='/grid/resources/org/openqa/grid/images/firefox.png' width='16' height='16' title='{server:CONFIG_UUID=3e72bd4c-f8e2-431b-b3fc-bd103dda68d3, seleniumProtocol=WebDriver, browserName=firefox, maxInstances=4, platformName=WIN10, platform=WIN10}' />
<img src='/grid/resources/org/openqa/grid/images/firefox.png' width='16' height='16' title='{server:CONFIG_UUID=3e72bd4c-f8e2-431b-b3fc-bd103dda68d3, seleniumProtocol=WebDriver, browserName=firefox, maxInstances=4, platformName=WIN10, platform=WIN10}' />
<img src='/grid/resources/org/openqa/grid/images/firefox.png' width='16' height='16' title='{server:CONFIG_UUID=3e72bd4c-f8e2-431b-b3fc-bd103dda68d3, seleniumProtocol=WebDriver, browserName=firefox, maxInstances=4, platformName=WIN10, platform=WIN10}' />
</p><p>v:<img src='/grid/resources/org/openqa/grid/images/chrome.png' width='16' height='16' title='{server:CONFIG_UUID=0d6870ce-56b2-409e-8baf-af4df9e7059c, seleniumProtocol=WebDriver, browserName=chrome, maxInstances=3, platformName=WIN10, platform=WIN10}' />
<img src='/grid/resources/org/openqa/grid/images/chrome.png' width='16' height='16' title='{server:CONFIG_UUID=0d6870ce-56b2-409e-8baf-af4df9e7059c, seleniumProtocol=WebDriver, browserName=chrome, maxInstances=3, platformName=WIN10, platform=WIN10}' />
<img src='/grid/resources/org/openqa/grid/images/chrome.png' width='16' height='16' title='{server:CONFIG_UUID=0d6870ce-56b2-409e-8baf-af4df9e7059c, seleniumProtocol=WebDriver, browserName=chrome, maxInstances=3, platformName=WIN10, platform=WIN10}' />
</p><p>v:<img src='/grid/resources/org/openqa/grid/images/internet_explorer.png' width='16' height='16' title='{server:CONFIG_UUID=aa4d88d7-f0aa-4e1e-8b4f-9ee2fdf897f9, seleniumProtocol=WebDriver, browserName=iexplore, platformName=WIN10, platform=WIN10}' />
</p></div><div type='config' class='content_detail'><p>browserTimeout: 0</p><p>debug: false</p><p>host: 192.168.1.100</p><p>port: 5555</p><p>role: node</p><p>timeout: 1800</p><p>cleanUpCycle: 5000</p><p>maxSession: 4</p><p>capabilities: Capabilities {browserName: firefox, maxInstances: 4, platform: WIN10, platformName: WIN10, seleniumProtocol: WebDriver, server:CONFIG_UUID: 3e72bd4c-f8e2-431b-b3fc-bd1...}</p><p>capabilities: Capabilities {browserName: iexplore, platform: WIN10, platformName: WIN10, seleniumProtocol: WebDriver, server:CONFIG_UUID: aa4d88d7-f0aa-4e1e-8b4f-9ee...}</p><p>capabilities: Capabilities {browserName: chrome, maxInstances: 3, platform: WIN10, platformName: WIN10, seleniumProtocol: WebDriver, server:CONFIG_UUID: 0d6870ce-56b2-409e-8baf-af4...}</p><p>downPollingLimit: 2</p><p>hub: http://localhost:4444/grid/register</p><p>id: http://192.168.1.100:5555</p><p>nodePolling: 5000</p><p>nodeStatusCheckTimeout: 5000</p><p>proxy: org.openqa.grid.selenium.proxy.DefaultRemoteProxy</p><p>register: true</p><p>registerCycle: 5000</p><p>remoteHost: http://192.168.1.100:5555</p><p>unregisterIfStillDownAfter: 60000</p></div></div></div></div><div id='right-column'></div><div class='clearfix'></div><div><ul></ul></div><div id='hub-config-container'><div id='hub-config-content'><b>Config for the hub :</b><br/><abbr title='browserTimeout'>browserTimeout : </abbr>0</br><abbr title='debug'>debug : </abbr>false</br><abbr title='host'>host : </abbr>192.168.1.100</br><abbr title='port'>port : </abbr>4444</br><abbr title='role'>role : </abbr>hub</br><abbr title='timeout'>timeout : </abbr>1800</br><abbr title='cleanUpCycle'>cleanUpCycle : </abbr>5000</br><abbr title='capabilityMatcher'>capabilityMatcher : </abbr>org.openqa.grid.internal.utils.DefaultCapabilityMatcher</br><abbr title='newSessionWaitTimeout'>newSessionWaitTimeout : </abbr>-1</br><abbr title='throwOnCapabilityNotPresent'>throwOnCapabilityNotPresent : </abbr>true</br><abbr title='registry'>registry : </abbr>org.openqa.grid.internal.DefaultGridRegistry</br><div id='verbose-config-container'><a id='verbose-config-view-toggle' href='#'>View Verbose</a><div id='verbose-config-content'><br/><b>The final configuration comes from:</b><br/><b>the default :</b><br/><abbr title='browserTimeout'>browserTimeout : </abbr>0</br><abbr title='debug'>debug : </abbr>false</br><abbr title='host'>host : </abbr>0.0.0.0</br><abbr title='port'>port : </abbr>4444</br><abbr title='role'>role : </abbr>hub</br><abbr title='timeout'>timeout : </abbr>1800</br><abbr title='cleanUpCycle'>cleanUpCycle : </abbr>5000</br><abbr title='capabilityMatcher'>capabilityMatcher : </abbr>org.openqa.grid.internal.utils.DefaultCapabilityMatcher</br><abbr title='newSessionWaitTimeout'>newSessionWaitTimeout : </abbr>-1</br><abbr title='throwOnCapabilityNotPresent'>throwOnCapabilityNotPresent : </abbr>true</br><abbr title='registry'>registry : </abbr>org.openqa.grid.internal.DefaultGridRegistry</br><b>updated with command line options:</b><br/>-role hub</div></div></div><a id='config-view-toggle' href='#'>View Config</a></div></div></body></html>
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at MyTryPackage.GridRunningTestWithGrid.doLogin(GridRunningTestWithGrid.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'LAPTOP-22R5VRV9', ip: '192.168.1.100', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:122)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:140)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:126)
	at org.openqa.selenium.json.Json.toType(Json.java:69)
	at org.openqa.selenium.json.Json.toType(Json.java:55)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:112)
	... 31 more

**My java code**  
package MyTryPackage;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;

import org.openqa.selenium.Platform;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.Test;
import org.testng.annotations.Parameters;

public class GridRunningTestWithGrid {
  
	public static WebDriver driver =null;
	public static DesiredCapabilities cap = new DesiredCapabilities();
	
	@Parameters({"browser"})
	@Test
	public void doLogin(String browser) throws MalformedURLException
	{  if(browser.equals("Chrome"))  
	   {
		  cap.setBrowserName("Chrome");
	      cap.setPlatform(Platform.ANY);
		
	      ChromeOptions option = new ChromeOptions();
	      option.merge(cap);
	   } else if(browser.equals("Firefox"))
	     {  cap.setBrowserName("Firefox");
		     cap.setPlatform(Platform.ANY);		   
	     }
	      
	      driver = new RemoteWebDriver(new URL("http://localhost:4444/grid/console"), cap);		
	      
	      driver.get("https://accounts.google.com/signin/v2/identifier?service=mail&flowName=GlifWebSignIn&flowEntry=ServiceLogin");
	      driver.manage().window().maximize();
	      driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	      
	      driver.findElement(By.xpath("//input[@type='email']")).sendKeys("tikarihamanisha123@gmail.com");
		  driver.findElement(By.xpath("//span[@class='RveJvd snByac']")).click();
		  
		  WebDriverWait wait = new WebDriverWait(driver, 15);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//input[@type='password']"))).sendKeys("tropical11617");		  
		  
		  driver.quit();
	}
}

**testng.xml**
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">

<suite name = "Grid Suite">
   <test name = "Grid Chrome Test">
      <parameter name="browser"  value="Chrome" />
      <classes>
         <class name="MyTryPackage.GridRunningTestWithGrid" />        
      </classes>   
   </test>
   
  <test name="Grid Firefox Test">
    <parameter name="browser"  value="Firefox" />
      <classes>
        <class name="MyTryPackage.GridRunningTestWithGrid" />
      </classes>
   </test> 
</suite>

**I am configuring hub and node in my laptop only , which has Windows 10 O.S.**

**I ran below command in command prompt to configure hub**
C:\Selenium Testing\Softwares>java -jar selenium-server-standalone-3.141.59.jar -role hub

**After hitting enter , it produced below lines**
 20:23:32.267 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
20:23:32.355 INFO [GridLauncherV3.lambda$buildLaunchers$5] - Launching Selenium Grid hub on port 4444
2019-09-10 20:23:32.784:INFO::main: Logging initialized @846ms to org.seleniumhq.jetty9.util.log.StdErrLog
20:23:33.155 INFO [Hub.start] - Selenium Grid hub is up and running
20:23:33.157 INFO [Hub.start] - Nodes should register to http://192.168.1.100:4444/grid/register/
20:23:33.157 INFO [Hub.start] - Clients should connect to http://192.168.1.100:4444/wd/hub
20:35:00.172 WARN [BaseRemoteProxy.<init>] - Max instance not specified. Using default = 1 instance
20:35:00.192 INFO [DefaultGridRegistry.add] - Registered a node http://192.185.1.100:5555

**I ran below command in command prompt to configure node**
C:\Selenium Testing\Softwares>Java -Dwebdriver.chrome.driver=chromedriver.exe -Dwebdriver.gecko.driver=geckodriver.exe -Dwebdriver.ie.driver=IEDriverServer.exe -jar selenium-server-standalone-3.141.59.jar -role webdriver -hub http://localhost:4444/grid/register -port 5555 -browser browserName=firefox,maxInstances=4 -browser browserName=iexplore -browser browserName=chrome,maxInstances=3 -maxSession 4

**After hitting enter , it produced below lines**
20:34:58.291 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
20:34:58.397 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 5555
2019-09-10 20:34:58.787:INFO::main: Logging initialized @732ms to org.seleniumhq.jetty9.util.log.StdErrLog
20:34:59.018 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
20:34:59.096 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
20:34:59.096 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
20:34:59.239 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
20:34:59.776 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://localhost:4444/grid/register
20:35:00.197 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use

Please let me know, If I am missing any detail. I will provide that too.

**Comment by QA-Selenium** [comment]
Please go thru the document "Error in Detail.txt" , if error detail is not clear in my previous post.
[Error in Detail.txt](https://github.com/QA-Selenium/Sample/files/3598882/Error.in.Detail.txt)

Also please find testng.xml file in attachment
[testng.xml.txt](https://github.com/QA-Selenium/Sample/files/3598969/testng.xml.txt)
